name: "Build NixOS-WSL"
on:
  pull_request:
  push:
jobs:
  build:
    defaults:
      run:
        working-directory: ./hosts/tinkerbell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build tarballBuilder
      run: nix build .#nixosConfigurations.tinkerbell.config.system.build.tarballBuilder
    - name: Run tarballBuilder
      run: sudo ./result/bin/tarballBuilder nixos-wsl-tinkerbell.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: tarball
        path: nixos-wsl-tinkerbell.tar.gz
